-- Migration 0039: Categoriser taxonomy cleanup (Layer 3)
--
-- Generated by scripts/categoriser-cleanup-apply.mjs from
-- scripts/categoriser-cleanup-plan.json (operator-edited).
--
-- See docs/DECISIONS.md 2026-05-07 "Categoriser fragmentation fix"
-- for the architectural context. Layer 1+2 (contract rewrite +
-- recent-headlines signal) shipped in the prior commit; this
-- migration handles the existing 26-category mess by collapsing
-- into 10 domain-level single-word categories.
--
-- Forward-only. The fallback category (patterns-yet-to-cluster)
-- and any other category the plan does not explicitly retire are
-- preserved. This migration is operator-curated — confidence on
-- new piece_categories rows is set to 100.

-- 1. INSERT new operator-curated target categories.
INSERT INTO categories (id, slug, name, description, locked, piece_count, created_at, updated_at)
VALUES ('a2986354-8301-4368-9c88-7f7122e43a9b', 'brain', 'Brain', 'Neuroscience, brain anatomy, neural circuits, learning, memory, and how the nervous system processes signals and adapts structure.', 1, 0, 1778180584918, 1778180584918);
INSERT INTO categories (id, slug, name, description, locked, piece_count, created_at, updated_at)
VALUES ('34dc6842-b537-43fa-b761-8351844594e4', 'biology', 'Biology', 'Cellular biology, genetics, evolution, physiology, immunology, and how living systems function and adapt.', 1, 0, 1778180584918, 1778180584918);
INSERT INTO categories (id, slug, name, description, locked, piece_count, created_at, updated_at)
VALUES ('9df0b6b4-a323-4484-9082-9d7cd46f56f1', 'ecology', 'Ecology', 'Ecosystems, species interactions, invasive species, environmental adaptation, and how organisms shape and respond to their habitats.', 1, 0, 1778180584918, 1778180584918);
INSERT INTO categories (id, slug, name, description, locked, piece_count, created_at, updated_at)
VALUES ('880b937e-ae28-4211-90f1-1c0f58b39d54', 'trade', 'Trade', 'International trade, tariffs, supply chains, commodity markets, chokepoints, cartels, and the economics of global commerce.', 1, 0, 1778180584918, 1778180584918);
INSERT INTO categories (id, slug, name, description, locked, piece_count, created_at, updated_at)
VALUES ('10761368-b308-4b6a-b371-83517e1090f8', 'infrastructure', 'Infrastructure', 'Critical systems including transportation, utilities, data centers, cybersecurity, and the challenges of maintaining and modernizing essential networks.', 1, 0, 1778180584918, 1778180584918);
INSERT INTO categories (id, slug, name, description, locked, piece_count, created_at, updated_at)
VALUES ('5ec314ef-0478-49b1-8f69-4fa066a0a06b', 'governance', 'Governance', 'Policy design, lawmaking, elections, legitimacy, institutional accountability, and how governments structure authority and outcomes.', 1, 0, 1778180584918, 1778180584918);
INSERT INTO categories (id, slug, name, description, locked, piece_count, created_at, updated_at)
VALUES ('5c13395d-3d38-4adc-9203-9270a1e7bdc3', 'justice', 'Justice', 'Law enforcement, criminal justice, punishment, execution methods, institutional failure in policing and corrections.', 1, 0, 1778180584918, 1778180584918);
INSERT INTO categories (id, slug, name, description, locked, piece_count, created_at, updated_at)
VALUES ('04c725b2-f26c-4eee-8255-928729a9d233', 'business', 'Business', 'Corporate strategy, business models, market competition, disruption, and how companies adapt to technological and economic change.', 1, 0, 1778180584918, 1778180584918);
INSERT INTO categories (id, slug, name, description, locked, piece_count, created_at, updated_at)
VALUES ('2c9eaa65-104c-43b8-b3da-b9e3ec682895', 'medicine', 'Medicine', 'Diagnosis, treatment, medical systems, end-of-life care, and how healthcare makes decisions under uncertainty.', 1, 0, 1778180584918, 1778180584918);
INSERT INTO categories (id, slug, name, description, locked, piece_count, created_at, updated_at)
VALUES ('aa9947bb-904e-410e-bee3-63c10b5acf93', 'science', 'Science', 'Scientific discovery, research methods, fossil records, astronomy, physics, paleontology, and basic research findings across disciplines.', 1, 0, 1778180584918, 1778180584918);

-- 2. Delete all existing piece_categories rows for pieces being
--    reassigned. Cleaner than per-row UPDATEs when target counts
--    differ from source counts; we rebuild from scratch in step 3.
DELETE FROM piece_categories WHERE piece_id IN (
  '59a7f53b-9a32-443e-bfa3-27af4471bbff',
  '9ded9bec-1616-4552-b8a5-e69f1e446466',
  'b6f857ea-f75a-474d-a933-a029238c05e5',
  '5f45b905-2eff-42ac-84f7-fa8adf41c477',
  'ab95f0f8-b419-4e2e-95a8-46ca0290957a',
  '726b2abf-d4e2-4156-8b66-7c2b9dd2623d',
  '878def34-3407-4bf7-9d1f-93c48511e3ca',
  'c7fb29ed-7a22-47c1-a4a4-a85ac20b77be',
  'abf52fe5-de75-4e3a-bba4-6bb98858bc1d',
  'd047cd76-6e35-42ec-b8ed-35d675c42339',
  '71e2f879-0578-4618-8766-33c6f3ce19a8',
  '06a9524c-115c-4853-9aa3-478b68fcd1dd',
  '7eb5f8a3-29d2-4059-94a9-bb88904f3cf7',
  '264ea451-d3f2-42b2-893f-037af8555ea1',
  '9280146e-16ad-4c7a-977a-1900dc9b3324',
  'cee5e838-4718-4847-a229-b9271b6cb7ea',
  '2f1d9adf-66ac-42ac-80c6-230a72bb8fdc',
  '871db594-7344-4fcd-bdaf-d410fa29d73c',
  'e55021d2-da15-4aec-a21b-3c691e62372d',
  'b4ffbd42-cd10-484e-b92e-3085f2303266',
  'ad0c68c2-d745-4cde-b776-faf7feb554d0',
  'c0b08dee-c011-44d7-acc2-78ecc3c2f7a6',
  'b00d9a30-65e6-4c6e-9b96-da7d8d9dcbe9',
  '2fb4bb9e-1918-4a84-8e80-ad1974b8bcf4',
  '2aba2c5f-0a3e-4c61-a3e2-8dddfc7945e7',
  '5d0918d4-9800-45b1-9e96-17b181a1c3fb',
  '8347b741-20d1-44bf-9d85-f4868d215dd4',
  '280dc1c7-5a72-4928-aef7-123e19996fb4',
  'fd644822-c6c6-4c23-811b-a6cef4e203fc',
  '99b4187f-7a66-4a1b-be9c-5d406017c1f2',
  '6e55caab-d026-4286-944f-03f30d4bdf76',
  '97b506b4-9eab-49bb-a321-5db39790b9cc',
  'c6cc7d96-9ad5-4622-9666-912fbf9df3f1',
  '086ad49c-c549-4931-9a26-244f319ac3df',
  '4151bae5-320c-437d-ad38-b2bb7d003b67',
  '62ae4989-cea9-4abc-8696-f554cd78ad95',
  'b77e8406-a000-46ef-8989-dde9bb48a8b4',
  '13ba1f76-4494-464f-80e9-59e716541419',
  '45fd292c-4e38-4f82-b7af-550faac3aaa4',
  '1837d250-d1bb-4002-9160-40ac0500d673',
  'a204d497-fbcd-480d-ba91-3b1549d534c3',
  '7b1cddee-d352-4664-a204-f6e49ff966bf',
  'ee3a82fd-c06a-4557-bfb2-f6b261e6ba07',
  '088db2c2-9b0b-4f9e-a0d3-6f7492b6a108',
  'bb305ff6-936e-4d4f-a0fa-7200787ae669',
  '24105499-7103-437c-b231-d40bdaae5bb1',
  '45921a12-0156-478f-b8ab-7d9534f87439',
  'f100b863-b6fa-4a48-84ec-190d038c5e96',
  'd3f724bd-5933-40a2-b078-0a317d05425b'
);

-- 3. INSERT fresh piece_categories rows per the cleanup plan.
--    Confidence=100 means operator-curated.
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('59a7f53b-9a32-443e-bfa3-27af4471bbff', '04c725b2-f26c-4eee-8255-928729a9d233', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('9ded9bec-1616-4552-b8a5-e69f1e446466', '880b937e-ae28-4211-90f1-1c0f58b39d54', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('b6f857ea-f75a-474d-a933-a029238c05e5', '880b937e-ae28-4211-90f1-1c0f58b39d54', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('b6f857ea-f75a-474d-a933-a029238c05e5', '04c725b2-f26c-4eee-8255-928729a9d233', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('5f45b905-2eff-42ac-84f7-fa8adf41c477', '880b937e-ae28-4211-90f1-1c0f58b39d54', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('ab95f0f8-b419-4e2e-95a8-46ca0290957a', '880b937e-ae28-4211-90f1-1c0f58b39d54', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('726b2abf-d4e2-4156-8b66-7c2b9dd2623d', '10761368-b308-4b6a-b371-83517e1090f8', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('878def34-3407-4bf7-9d1f-93c48511e3ca', '5ec314ef-0478-49b1-8f69-4fa066a0a06b', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('c7fb29ed-7a22-47c1-a4a4-a85ac20b77be', 'aa9947bb-904e-410e-bee3-63c10b5acf93', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('abf52fe5-de75-4e3a-bba4-6bb98858bc1d', '5ec314ef-0478-49b1-8f69-4fa066a0a06b', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('d047cd76-6e35-42ec-b8ed-35d675c42339', '880b937e-ae28-4211-90f1-1c0f58b39d54', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('71e2f879-0578-4618-8766-33c6f3ce19a8', '5ec314ef-0478-49b1-8f69-4fa066a0a06b', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('06a9524c-115c-4853-9aa3-478b68fcd1dd', '10761368-b308-4b6a-b371-83517e1090f8', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('06a9524c-115c-4853-9aa3-478b68fcd1dd', '5ec314ef-0478-49b1-8f69-4fa066a0a06b', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('7eb5f8a3-29d2-4059-94a9-bb88904f3cf7', '5c13395d-3d38-4adc-9203-9270a1e7bdc3', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('264ea451-d3f2-42b2-893f-037af8555ea1', '5ec314ef-0478-49b1-8f69-4fa066a0a06b', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('9280146e-16ad-4c7a-977a-1900dc9b3324', '880b937e-ae28-4211-90f1-1c0f58b39d54', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('cee5e838-4718-4847-a229-b9271b6cb7ea', '9df0b6b4-a323-4484-9082-9d7cd46f56f1', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('2f1d9adf-66ac-42ac-80c6-230a72bb8fdc', '2c9eaa65-104c-43b8-b3da-b9e3ec682895', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('871db594-7344-4fcd-bdaf-d410fa29d73c', '5c13395d-3d38-4adc-9203-9270a1e7bdc3', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('e55021d2-da15-4aec-a21b-3c691e62372d', 'aa9947bb-904e-410e-bee3-63c10b5acf93', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('b4ffbd42-cd10-484e-b92e-3085f2303266', '880b937e-ae28-4211-90f1-1c0f58b39d54', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('ad0c68c2-d745-4cde-b776-faf7feb554d0', 'a2986354-8301-4368-9c88-7f7122e43a9b', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('c0b08dee-c011-44d7-acc2-78ecc3c2f7a6', '5ec314ef-0478-49b1-8f69-4fa066a0a06b', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('b00d9a30-65e6-4c6e-9b96-da7d8d9dcbe9', '9df0b6b4-a323-4484-9082-9d7cd46f56f1', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('2fb4bb9e-1918-4a84-8e80-ad1974b8bcf4', '5ec314ef-0478-49b1-8f69-4fa066a0a06b', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('2aba2c5f-0a3e-4c61-a3e2-8dddfc7945e7', 'aa9947bb-904e-410e-bee3-63c10b5acf93', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('5d0918d4-9800-45b1-9e96-17b181a1c3fb', '2c9eaa65-104c-43b8-b3da-b9e3ec682895', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('8347b741-20d1-44bf-9d85-f4868d215dd4', '5c13395d-3d38-4adc-9203-9270a1e7bdc3', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('280dc1c7-5a72-4928-aef7-123e19996fb4', 'aa9947bb-904e-410e-bee3-63c10b5acf93', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('fd644822-c6c6-4c23-811b-a6cef4e203fc', '5ec314ef-0478-49b1-8f69-4fa066a0a06b', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('99b4187f-7a66-4a1b-be9c-5d406017c1f2', '10761368-b308-4b6a-b371-83517e1090f8', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('6e55caab-d026-4286-944f-03f30d4bdf76', '5ec314ef-0478-49b1-8f69-4fa066a0a06b', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('97b506b4-9eab-49bb-a321-5db39790b9cc', '5c13395d-3d38-4adc-9203-9270a1e7bdc3', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('c6cc7d96-9ad5-4622-9666-912fbf9df3f1', '34dc6842-b537-43fa-b761-8351844594e4', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('086ad49c-c549-4931-9a26-244f319ac3df', 'a2986354-8301-4368-9c88-7f7122e43a9b', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('086ad49c-c549-4931-9a26-244f319ac3df', '2c9eaa65-104c-43b8-b3da-b9e3ec682895', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('4151bae5-320c-437d-ad38-b2bb7d003b67', 'a2986354-8301-4368-9c88-7f7122e43a9b', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('62ae4989-cea9-4abc-8696-f554cd78ad95', 'aa9947bb-904e-410e-bee3-63c10b5acf93', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('b77e8406-a000-46ef-8989-dde9bb48a8b4', '2c9eaa65-104c-43b8-b3da-b9e3ec682895', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('13ba1f76-4494-464f-80e9-59e716541419', 'aa9947bb-904e-410e-bee3-63c10b5acf93', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('45fd292c-4e38-4f82-b7af-550faac3aaa4', 'aa9947bb-904e-410e-bee3-63c10b5acf93', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('1837d250-d1bb-4002-9160-40ac0500d673', '34dc6842-b537-43fa-b761-8351844594e4', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('a204d497-fbcd-480d-ba91-3b1549d534c3', '34dc6842-b537-43fa-b761-8351844594e4', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('a204d497-fbcd-480d-ba91-3b1549d534c3', '2c9eaa65-104c-43b8-b3da-b9e3ec682895', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('7b1cddee-d352-4664-a204-f6e49ff966bf', 'aa9947bb-904e-410e-bee3-63c10b5acf93', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('ee3a82fd-c06a-4557-bfb2-f6b261e6ba07', '34dc6842-b537-43fa-b761-8351844594e4', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('088db2c2-9b0b-4f9e-a0d3-6f7492b6a108', 'aa9947bb-904e-410e-bee3-63c10b5acf93', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('bb305ff6-936e-4d4f-a0fa-7200787ae669', 'aa9947bb-904e-410e-bee3-63c10b5acf93', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('24105499-7103-437c-b231-d40bdaae5bb1', 'a2986354-8301-4368-9c88-7f7122e43a9b', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('45921a12-0156-478f-b8ab-7d9534f87439', 'aa9947bb-904e-410e-bee3-63c10b5acf93', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('f100b863-b6fa-4a48-84ec-190d038c5e96', 'a2986354-8301-4368-9c88-7f7122e43a9b', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('d3f724bd-5933-40a2-b078-0a317d05425b', '34dc6842-b537-43fa-b761-8351844594e4', 100, 1778180584918);
INSERT INTO piece_categories (piece_id, category_id, confidence, created_at) VALUES ('d3f724bd-5933-40a2-b078-0a317d05425b', '2c9eaa65-104c-43b8-b3da-b9e3ec682895', 100, 1778180584918);

-- 4. Delete old categories that now have zero piece_categories rows.
--    Filtering on the JOIN preserves piece_categories integrity (we
--    do NOT touch the audit trail). Old categories that some piece
--    still references are left untouched — operator can rerun the
--    cleanup if more pieces need migrating.
DELETE FROM categories WHERE slug IN (
  'knowledge-formation',
  'resource-constraints-tradeoffs',
  'measurement-detection-limits',
  'chokepoints-and-supply',
  'infrastructure-technical-debt',
  'pattern-recognition-sensing',
  'policy-design-implementation',
  'systems-under-stress',
  'commodity-shocks',
  'information-asymmetry-markets',
  'state-violence-justice-systems',
  'cartels-coordination-problems',
  'institutional-accountability',
  'business-model-disruption',
  'competition-and-credit',
  'death-dying-systems',
  'ecological-systems-invasive-species',
  'emergence-and-scale',
  'judicial-interpretation-institutional-change',
  'legislative-process',
  'legitimacy-contested-authority',
  'neural-architecture-specialization',
  'organizational-failure-recovery',
  'path-dependence-lock-in',
  'security-architecture-failure',
  'trade-policy-mechanics'
) AND id NOT IN (SELECT DISTINCT category_id FROM piece_categories);

-- 5. Recompute piece_count for every remaining category from the
--    actual piece_categories rows. Drift-recovery hatch baked into
--    the migration so we land in a known-good state.
UPDATE categories SET
  piece_count = (SELECT COUNT(*) FROM piece_categories WHERE category_id = categories.id),
  updated_at = 1778180584918;

